# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_manager',
            name='id',
        ),
        migrations.AddField(
            model_name='card_manager',
            name='unique_id',
            field=models.CharField(default='6Hr41tKrTLdzBJJ3j3znrPKJPz4wT0Em', max_length=32, primary_key=True, serialize=False),
        ),
    ]
